// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoAppAPI.Data;

#nullable disable

namespace TodoAppAPI.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoAppAPI.Models.Activity", b =>
                {
                    b.Property<string>("ActivUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ActivUId");

                    b.HasIndex("CardUId");

                    b.HasIndex("UserUId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Board", b =>
                {
                    b.Property<string>("BoardUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Private");

                    b.Property<string>("WorkspaceUId")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("BoardUId");

                    b.HasIndex("WorkspaceUId");

                    b.HasIndex("UserUId", "IsPersonal");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.BoardMember", b =>
                {
                    b.Property<string>("BoardMemberUId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BoardRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Viewer");

                    b.Property<string>("BoardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("InvitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("BoardMemberUId");

                    b.HasIndex("UserUId");

                    b.HasIndex("BoardUId", "UserUId")
                        .IsUnique();

                    b.ToTable("BoardMembers", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Card", b =>
                {
                    b.Property<string>("CardUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListUId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("To Do");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CardUId");

                    b.HasIndex("ListUId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Comment", b =>
                {
                    b.Property<string>("CommentUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserUId")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("CommentUId");

                    b.HasIndex("CardUId");

                    b.HasIndex("UserUId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.List", b =>
                {
                    b.Property<string>("ListUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BoardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("ListUId");

                    b.HasIndex("BoardUId");

                    b.ToTable("Lists", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "System Administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Regular User",
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Guest User",
                            RoleName = "Guest"
                        });
                });

            modelBuilder.Entity("TodoAppAPI.Models.TodoItem", b =>
                {
                    b.Property<string>("TodoItemUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.HasKey("TodoItemUId");

                    b.HasIndex("CardUId");

                    b.ToTable("TodoItems", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.User", b =>
                {
                    b.Property<string>("UserUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserUId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserInboxCard", b =>
                {
                    b.Property<string>("UserUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CardUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("UserUId", "CardUId");

                    b.HasIndex("CardUId");

                    b.ToTable("UserInboxCards", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserRecentBoard", b =>
                {
                    b.Property<string>("UserRecentBoardUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BoardUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("LastVisitedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserRecentBoardUId");

                    b.HasIndex("BoardUId");

                    b.HasIndex("LastVisitedAt");

                    b.HasIndex("UserUId");

                    b.ToTable("UserRecentBoard", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Workspace", b =>
                {
                    b.Property<string>("WorkspaceUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("WorkspaceUId");

                    b.HasIndex("OwnerUId");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkspaceMember", b =>
                {
                    b.Property<string>("WorkspaceMemberUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Member");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkspaceUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("WorkspaceMemberUId");

                    b.HasIndex("UserUId");

                    b.HasIndex("WorkspaceUId", "UserUId")
                        .IsUnique();

                    b.ToTable("WorkspaceMembers", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Activity", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany("Activities")
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Board", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("OwnedBoards")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.Workspace", "Workspace")
                        .WithMany("Boards")
                        .HasForeignKey("WorkspaceUId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TodoAppAPI.Models.BoardMember", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Board", "Board")
                        .WithMany("Members")
                        .HasForeignKey("BoardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("BoardMemberships")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Card", b =>
                {
                    b.HasOne("TodoAppAPI.Models.List", "List")
                        .WithMany("Cards")
                        .HasForeignKey("ListUId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("List");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Comment", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany("Comments")
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.List", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Board", "Board")
                        .WithMany("Lists")
                        .HasForeignKey("BoardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("TodoAppAPI.Models.TodoItem", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany("TodoItems")
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TodoAppAPI.Models.User", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserInboxCard", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany("UserInboxCards")
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("InboxCards")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserRecentBoard", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Workspace", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "Owner")
                        .WithMany("OwnedWorkspaces")
                        .HasForeignKey("OwnerUId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkspaceMember", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Board", b =>
                {
                    b.Navigation("Lists");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Card", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Comments");

                    b.Navigation("TodoItems");

                    b.Navigation("UserInboxCards");
                });

            modelBuilder.Entity("TodoAppAPI.Models.List", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TodoAppAPI.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("BoardMemberships");

                    b.Navigation("Comments");

                    b.Navigation("InboxCards");

                    b.Navigation("OwnedBoards");

                    b.Navigation("OwnedWorkspaces");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Workspace", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
